### ISSUE TITLE
text 频繁的属性变更会导致性能问题

### ISSUE THREAD

**Issue by yangxin9003** [webfansplz/temir#11]
例子：
https://replit.com/@yangxin9003/temir-list-test?v=1

child.vue 组建切换注释的模版代码
![image](https://user-images.githubusercontent.com/3380299/186375978-b24fb979-e49c-47ea-bbc2-bb5a4363dbc4.png)

现象：
在属性更新时，随着时间推移性能逐渐下降
只有children文本更新时，性能没有下降

排查出的问题：
随着 list 中 数据 的 active 属性的逐一变更，导致了之前变更过的 child.vue 组建发生 update。原因不明

大量组建的update性能也有些问题，排查感觉和 updadte 时 vnode的props 的 diff 导致的频繁的onRender调用有关系。

**Comment by webfansplz** [comment]
Good Catch ! 感谢反馈 ! 我找个时间看看.

**Comment by webfansplz** [comment]
Fixed in v0.0.11
