### ISSUE TITLE
计划新增 Tree 组件和 Progress 组件吗？

### ISSUE THREAD

**Issue by noootwo** [webfansplz/temir#14]
- Tree组件
类似于ui组件库中的 Tree 组件，用快捷键操作，可以用于文件夹目录展示等场景。
- Progress组件
各种场景下的进度条。

如果有类似计划，我可以尝试 contribute。

**Comment by webfansplz** [comment]
感谢反馈,让我们在https://github.com/vue-terminal/vue-termui  跟踪它.
